/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CodeDeliveryDetailsResponse {
    /**
    * The location the code has been sent to
    */
    'destination': string;
    /**
    * The way the code was send
    */
    'deliveryMedium': string;
    /**
    * The name of the attribute
    */
    'attributeName': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "destination",
            "baseName": "Destination",
            "type": "string"
        },
        {
            "name": "deliveryMedium",
            "baseName": "DeliveryMedium",
            "type": "string"
        },
        {
            "name": "attributeName",
            "baseName": "AttributeName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CodeDeliveryDetailsResponse.attributeTypeMap;
    }
}

