/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum ERoles {
    Ga = <any> 'GA',
    Oa = <any> 'OA',
    Sa = <any> 'SA',
    M = <any> 'M',
    O = <any> 'O',
    W = <any> 'W',
    Sm = <any> 'SM'
}
