/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AttributeResponse } from './attributeResponse';

export class RefreshTokenResponse {
    /**
    * Access Token
    */
    'accessToken': string;
    /**
    * ID Token
    */
    'idToken': string;
    /**
    * User ID
    */
    'userId': string;
    /**
    * Array of attributes
    */
    'userAttributes': Array<AttributeResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "idToken",
            "baseName": "idToken",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "userAttributes",
            "baseName": "userAttributes",
            "type": "Array<AttributeResponse>"
        }    ];

    static getAttributeTypeMap() {
        return RefreshTokenResponse.attributeTypeMap;
    }
}

