/**
 * ManageSpace Auth API
 * ManageSpace Auth API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RolePermissionResponse {
    /**
    * Permission ID
    */
    'permissionId': number;
    '_function': string;
    /**
    * Detailed description.
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "permissionId",
            "baseName": "permissionId",
            "type": "number"
        },
        {
            "name": "_function",
            "baseName": "function",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RolePermissionResponse.attributeTypeMap;
    }
}

